### ISSUE TITLE
Stable?

### ISSUE THREAD

**Issue by Biceeeeepss** [gnif/SteamQueryProxy#1]
Hey,

I see this is a new project, but I want to ask if this is stable as I get an error with an Counter-Strike (1.6) Server.

This is the error:
```
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
```
Settings are fine, but it seems that can't get data from gameserver.

**Comment by gnif** [comment]
Hi,

At this time this project has not yet been tested with any other title then Rust. That said the error you're presenting here looks more like an issue with how you have configured the firewall. Please show the output of `iptables -nvL`

Also note this project is literally a few days old, so while it's been operating stable for the server I have here, I would still consider this project experimental at best.

**Comment by gnif** [comment]
Closing due to lack of information
