### ISSUE TITLE
recvfrom A2S_INFO: Resource temporarily unavailable

### ISSUE THREAD

**Issue by dimkazai4enko96** [gnif/SteamQueryProxy#4]
How to fix?

./SteamQueryProxy ***.***.**.** 27015
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable

./SteamQueryProxy 0 27015 It also gives the same error

**Comment by gnif** [comment]
No idea, you have provided exactly zero information.

**Comment by dimkazai4enko96** [comment]
Thanks a lot for the quick response. What other information is needed? I run SteamQueryProxy and get this log. Here is more information:

- OS Linux Debian 11
- Game Counter-Strike Source v92
- SteamQueryProxy compiled successfully

make
Scanning dependencies of target SteamQueryProxy
[ 50%] Building C object CMakeFiles/SteamQueryProxy.dir/src/main.c.o
[100%] Linking C executable SteamQueryProxy
[100%] Built target SteamQueryProxy

**Comment by gnif** [comment]
This has not been tested with CS, see #1 
Please provide your firewall rules

`Resource temporarily unavailable` indicates there was no data to read from the socket.

**Comment by dimkazai4enko96** [comment]
I use a clean OS, there are no rules. iptables -nvL
-bash: iptables: command not found

There is no security in front of the server either. Checked on different nodes and hosting

**Comment by gnif** [comment]
Please read the instructions in `README.md`, you MUST setup firewall rules for this to operate.
https://github.com/gnif/SteamQueryProxy#usage

**Comment by dimkazai4enko96** [comment]
Sorry for the inattention. I checked on the node with the rules, there was the same error. That's the only reason I decided to test it on another clean node. Now I installed iptables and added the rules:

<details><summary>Details</summary>
<p>

root@dimkazai4enko96:~/SteamQueryProxy/build# iptables -nvL
-bash: iptables: command not found
root@dimkazai4enko96:~/SteamQueryProxy/build# apt install iptables
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libip6tc2 libnetfilter-conntrack3
Suggested packages:
  firewalld
The following NEW packages will be installed:
  iptables libip6tc2 libnetfilter-conntrack3
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 458 kB of archives.
After this operation, 2,808 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://mirror.docker.ru/debian bullseye/main amd64 libip6tc2 amd64 1.8.7-1 [35.0 kB]
Get:2 http://mirror.docker.ru/debian bullseye/main amd64 libnetfilter-conntrack3 amd64 1.0.8-3 [40.6 kB]
Get:3 http://mirror.docker.ru/debian bullseye/main amd64 iptables amd64 1.8.7-1 [382 kB]
Fetched 458 kB in 0s (5,352 kB/s)
Selecting previously unselected package libip6tc2:amd64.
(Reading database ... 45418 files and directories currently installed.)
Preparing to unpack .../libip6tc2_1.8.7-1_amd64.deb ...
Unpacking libip6tc2:amd64 (1.8.7-1) ......................................................................................................................................................................................................................................] 
Selecting previously unselected package libnetfilter-conntrack3:amd64.....................................................................................................................................................................................................] 
Preparing to unpack .../libnetfilter-conntrack3_1.0.8-3_amd64.deb ...
Unpacking libnetfilter-conntrack3:amd64 (1.0.8-3) ...######################...............................................................................................................................................................................................] 
Selecting previously unselected package iptables.#############################################............................................................................................................................................................................] 
Preparing to unpack .../iptables_1.8.7-1_amd64.deb ...
Unpacking iptables (1.8.7-1) ...#################################################################################.........................................................................................................................................................] 
Setting up libip6tc2:amd64 (1.8.7-1) ...############################################################################################......................................................................................................................................] 
Setting up libnetfilter-conntrack3:amd64 (1.0.8-3) ...####################################################################################################################................................................................................................] 
Setting up iptables (1.8.7-1) ...###############################################################################################################################################################################..........................................................] 
update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in auto mode#########################################################################################################################.......................................] 
update-alternatives: using /usr/sbin/ip6tables-legacy to provide /usr/sbin/ip6tables (ip6tables) in auto mode
update-alternatives: using /usr/sbin/iptables-nft to provide /usr/sbin/iptables (iptables) in auto mode
update-alternatives: using /usr/sbin/ip6tables-nft to provide /usr/sbin/ip6tables (ip6tables) in auto mode
update-alternatives: using /usr/sbin/arptables-nft to provide /usr/sbin/arptables (arptables) in auto mode
update-alternatives: using /usr/sbin/ebtables-nft to provide /usr/sbin/ebtables (ebtables) in auto mode
Processing triggers for man-db (2.9.4-2) ...##########################################################################################################################################################################################################....................] 
Processing triggers for libc-bin (2.31-13+deb11u6) ...
root@dimkazai4enko96:~/SteamQueryProxy/build# ^C
root@dimkazai4enko96:~/SteamQueryProxy/build# iptables -A INPUT -i lo -j ACCEPT
root@dimkazai4enko96:~/SteamQueryProxy/build# iptables -A INPUT -p udp -m udp --dport 27015 -m length --length 33:57 -j NFQUEUE --queue-num 0 --queue-bypass
root@dimkazai4enko96:~/SteamQueryProxy/build# ./SteamQueryProxy 0 27015
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
root@dimkazai4enko96:~/SteamQueryProxy/build# ^C
root@dimkazai4enko96:~/SteamQueryProxy/build# iptables -nvL
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    1    53 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0           
   13   561 NFQUEUE    udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:27015 length 33:57 NFQUEUE num 0 bypass

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
root@dimkazai4enko96:~/SteamQueryProxy/build# ./SteamQueryProxy my_ip 27015
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailabl

</p>
</details>

**Comment by gnif** [comment]
Firstly running `./SteamQueryProxy ...* 27015` is completely incorrect. The first parameter is the queue ID, not your IP.

` --queue-num 0` is this ID.

Again I am sorry but this has not been tested with CS and this is now the second report of this not working. Unless you're able to debug this directly yourself I can not offer any advice.

Please note that it's likely you do not need this at all. It was written to avoid a bug in the Rust game engine.

**Comment by dimkazai4enko96** [comment]
I also tried to run ./SteamQueryProxy 0 27015, still getting the error recvfrom A2S_INFO: Resource temporarily unavailable. I'm trying to use your development to protect DDoS attacks by Valve Source Engine (VSE DDoS Method). Recently, css servers have been heavily attacked, no protection helps. We look forward to your development.

**Comment by gnif** [comment]
This has nothing to do with protecting the server, this is not the tool you're looking for.

**Comment by S3thas** [comment]
Hello there, apologies for piggybacking on this issue thread, but i'm having the same issue for my Rust server:
```
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
recvfrom A2S_INFO: Resource temporarily unavailable
and it keeps repeating..
```
The command im trying to run is `./SteamQueryProxy 0 28016`

My Rust server port settings
```
DESCRIPTION  PORT   PROTOCOL
Game         28015  udp
Query        28016  udp
RCON         28017  tcp
App          28018  tcp
```

iptables have been configured using your suggested settings
```
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -p udp -m udp --dport 28016 -m length --length 33:57 -j NFQUEUE --queue-num 0 --queue-bypass
```
Current `iptables -nvL`:
```
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 335K   64M ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0
44023 2394K NFQUEUE    udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:28016 length 33:57 NFQUEUE num 0 bypass

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
```
Library versions:
```
cmake version 3.20.0
gcc version 11.3.0 (Ubuntu 22.04.1)
libnetfilter-queue-dev version 1.0.5-2
libmnl-dev version 1.0.4-3build2
```

**Comment by Saadar** [comment]
@gnif

**Comment by gnif** [comment]
Can you please provide a sample tcpdump of the traffic?

`tcpdump -i eth0 -s0 udp and port 28016 -w capture.pcap`

Adjusting `eth0` to your external network interface. Please upload the resulting `capture.pcap` file.

**Comment by gnif** [comment]
Sorry, a correction here, I need the loopback traffic

`tcpdump -i lo -s0 udp and port 28016 -w capture.pcap`

Also please provide the output of `netstat -nvlp | grep 28016`

**Comment by S3thas** [comment]
Sorry for the late reply, just woke up, here is the `netstat -nvlp | grep 28016`:
```
netstat: no support for `AF INET (sctp)' on this system.
netstat: no support for `AF INET (sctp)' on this system.
udp        0      0 149.202.88.144:28016    0.0.0.0:*                           154057/./RustDedica
netstat: no support for `AF IPX' on this system.
netstat: no support for `AF AX25' on this system.
netstat: no support for `AF X25' on this system.
netstat: no support for `AF NETROM' on this system.
netstat: no support for `AF ROSE' on this system.
```
I ran the `tcpdump -i lo -s0 udp and port 28016 -w capture.pcap` command and left it running for 2 minutes, while at the same time `./SteamQueryProxy 0 28016` was running (let me know if you need a longer than 2 minute log of tcpdump)
Since github doesn't support .pcap file type upload to the message, here is a [download link](https://www.dropbox.com/s/1mengnlhgp1l6gs/capture.pcap?dl=1)

**Comment by gnif** [comment]
I can already see the issue, Rust has bound to `149.202.88.144`, however `SteamQueryProxy` needs to connect to it on `127.0.0.1` (Loopback). Because it's bound to only `149.202.88.144` it will not be able to communicate. You need to adjust rust to instead bind to `0.0.0.0` which will allow both to work.

Note that this is also per the documentation for rust:
```
+server.ip | 0.0.0.0 | Sets the Server IP. Leave it to 0.0.0.0 unless you have multiple IPs.
```
Ref: https://developer.valvesoftware.com/wiki/Rust_Dedicated_Server

**Comment by S3thas** [comment]
Thank you, already restarted my server using `+app.listenip 0.0.0.0` it should be up in 2-3 minutes and i will test it afterwards and let you know how it works out, thank you once again for your help!

**Comment by gnif** [comment]
IIRC `app.listenip` is for the Rust companion App, not the rust server itself. You need to set `+server.ip 0.0.0.0`

**Comment by S3thas** [comment]
Works like a charm now, already receiving query requests:
```
Got A2S_PLAYER_REPLY: 6 bytes
Got A2S_RULES_REPLY: 1400 bytes
A2S_INFO 0x8e89f97d
A2S_INFO 0x8624849b
A2S_INFO 0x733fb69a
A2S_RULES 0x733fb69a
```
Edit: yes i meant `+server.ip 0.0.0.0`
Edit2: Thank you once again for helping me out with this, and for providing this resource, I'm really grateful <3
Edit3: Hopefully finally now i will resolve my issue with OVH dedicated that I've been having for the past year

**Comment by gnif** [comment]
Awesome

@dimkazai4enko96, even though I do not believe this will help with your DDoS issue, this might be the same reason it is not working for you. I would be curious to know if it does actually help in your situation.

**Comment by gnif** [comment]
@Saadar just note that this application has a 1400 byte limit for the rules packet, you are already either at the limit or exceeding it which may cause issues. I have never tested this

**Comment by S3thas** [comment]
It is probably because of server description being too long, I will try to compact it to only state most important things

**Comment by S3thas** [comment]
Yes, after shortening it, I'm already only at 1063 bytes on the rules packet, thanks for letting me know about the limit.

Would it be possible to increase the byte limit if for some reason I might need the longer description again?
And if its possible, would i only need to edit `Line 84: static char g_datagram[1400]` and `Line 485: uint8_t buffer[1400]` to a higher number on the `main.c` and compile the build again? (Apologies if i'm completely off about this, never had to deal with C language)
If it might cause any issues to increase the limit, that's okay too, I will keep everything as is, was just confirming.

**Comment by gnif** [comment]
No, this will not work, 1400 is the maximum reliable payload size for a UDP datagram, to allow for larger payloads the application complexity increases as it needs to then identify the subsequent packet and re-assemble the original payload.

**Comment by gnif** [comment]
@Saadar & @dimkazai4enko96  I will be pushing in a substantial refactor/redesign which not only will fix the 1400 byte packet size limitation, but also affords some performance improvements and some basic filtering of invalid IPs. This should help with VSE Flood issues.

Testing locally I am able to handle up to 400,000 packets per second before packet loss starts to occur.

Note, this is highly experimental and may break, it would be a good idea to keep the prior version around in case there are problems.

**Comment by S3thas** [comment]
Amazing, love your work, I will be definitely testing it.
I already saw a massive change between just using default setup on OVH and after I started using your Query Proxy

**Comment by gnif** [comment]
Changes pushed. Please note that the launch arguments have changed, see the output of `--help` for all options and some useful information.

I am going to close this issue as resolved, if you encounter any problems please feel free to open a new issue with the details.

**Comment by dimkazai4enko96** [comment]
Thank you very much. I'm trying to start a game server with the +ip and -ip options (game Game: Counter-Strike Source v92), I still have 0.0.0.0:* it in the netstat -nvlp | grep 27015

netstat -nvlp | grep 22022

tcp        0      0 my_game_server_ip:27015    0.0.0.0:*               LISTEN      133787/./srcds_linu 
udp     9216      0 my_game_server_ip:27015    0.0.0.0:*                           133787/./srcds_linu 

I have several IP addresses on my machine, each game server uses a dedicated one. Ports can be the same. Can you add a variable so that you can specify the ip address of the game server? For example ./SteamQueryProxy -s my_game_server_ip -p 27015 -n 0 -t 2

**Comment by gnif** [comment]
It's not as simple as adding a parameter, we need to use the loop-back address to avoid getting into a network routing loop in netfilter itself. There might be a way to make this work by marking packets to avoid the loop, but it's not something I have yet looked into.

I will look into if it's possible.

**Comment by gnif** [comment]
Hrmm, it seems this isn't actually an issue anymore since the redesign of the application. I will add the parameter but please note that it might cause a loop when used. Feedback on how successful it is would be greatly appreciated.

**Comment by gnif** [comment]
This has been done. Please note that while you could point this to an IP on a different system, it is useless to do so. The new argument is `-i` or `--query-ip`.

The only issue with the DoS side of things is that I do not have any game servers that are being attacked, would you be willing to collaborate by allowing me access to one of these targeted systems so I can improve this software? I understand there may be a trust issue here as such I encourage you to see my other repository "Looking Glass" and the associated website. I am a very well known and trusted figure in the FOSS development community.

If not, then no worries ;)

**Comment by dimkazai4enko96** [comment]
Yes, sure. I trust you and am very grateful. I got it right, I see:

./SteamQueryProxy -i my_ip -p 27015 -n 0 -s 100000000
Upstream: my_ip:27015 (Protocol: Source)
Got A2S_INFO_REPLY: 267 bytes
Got S2C_CHALLENGE: 0x9f349e1a
Got A2S_PLAYER_REPLY: 6 bytes

It remains to check everything in a real situation. My telegram: @buddy1337

**Comment by gnif** [comment]
Sorry I do not use telegram, but I am on discord. You can contact me there in the Looking Glass server
https://looking-glass.io/discord
